name: Bundle Python Application

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  bundle:
    name: Bundle for platform ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-20.04
          - windows-2019

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt

    - name: Bundle Application
      run: |
        pyinstaller run_whisper.spec

    - uses: actions/upload-artifact@v3
      with:
        path: dist
        retention-days: 1
