name: Bundle Python Application

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  bundle:
    name: Bundle for platform ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          #- windows-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt

    - name: Bundle Application (Linux)
      if: runner.os == 'Linux'
      run: |
        pyinstaller \
          --exclude-module readline \
          --additional-hooks-dir . \
          --add-data 'LICENSE.*:.' \
          run_whisper.py

    - name: Bundle Application (Windows)
      if: runner.os == 'Windows'
      run: |
        pyinstaller \
          --additional-hooks-dir . \
          --add-data 'LICENSE.*;.' \
          run_whisper.py

    - name: Create ZIP archive
      working-directory: dist
      run: |
        zip -r run_whisper.zip run_whisper

    - uses: actions/upload-artifact@v3
      with:
        path: dist/run_whisper.zip
        retention-days: 1
