name: Bundle Python Application

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  bundle:
    name: Bundle for platform ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - windows-2019

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --extra-index-url https://download.pytorch.org/whl/cu117 -r requirements.txt

    - name: Download models to bundle
      run: |
        python download_models.py tiny.en tiny base.en base small.en small

    - name: Bundle distribution
      run: |
        pyinstaller run_whisper.spec

    - name: Create bundle file list for installer
      shell: bash
      run: |
        python gen_list_files.py dist/run_whisper

    - name: Install NSISBI
      shell: bash
      run: |
        curl -kLSs https://sourceforge.net/projects/nsisbi/files/latest/download -o nsisbi.zip
        unzip nsisbi.zip

    - name: Create a Windows installer
      shell: bash
      run: |
        ./nsis-binary-7336-1/Bin/makensis.exe installer.nsi

    - uses: actions/upload-artifact@v3
      with:
        path: "whisper-standalone.exe"
        retention-days: 1
